#seperate-page value can be "true" OR "false"
seperate-page: true

excludePagesFromIndexList:
 - name: "index.html"
 - name: "navigation-dropdowns-1.html"
 - name: "navigation-dropdowns-2.html"
 - name: "navigation-dropdowns-3.html"
 - name: "navigation-dropdowns-with-search-logged-in.html"
 - name: "tabbed-navigation-variation1.html"
 - name: "tabbed-navigation-variation2.html"
 - name: "tabbed-navigation-variation3.html"
 - name: "tabbed-navigation-variation4.html"
 - name: "tabbed-navigation-variation5.html"
 - name: "tabbed-navigation-overview.html"
 - name: "tabbed-navigation-no-profile.html"
 - name: "inner/index.html"
 - name: "google-map-1.html"
 - name: "google-map-2.html"
 - name: "google-map-3.html"
 - name: "google-map-4.html"
 - name: "google-map-5.html"
 - name: "google-map-6.html"
 - name: "video-banner-alt.html"
 - name: "video-banner-alt-2.html"
 - name: "video-banner-alt-3.html"
 - name: "vertical-card-spotlight-1.html"
 - name: "vertical-card-spotlight-2.html"
 - name: "horizontal-card-spotlight-1.html"
 - name: "horizontal-card-spotlight-2.html"
 - name: "index-listing.html"
